"""empty message

Revision ID: 053e1c6ab477
Revises: eff90419b076
Create Date: 2017-01-23 17:24:35.912768

"""

# revision identifiers, used by Alembic.
revision = '053e1c6ab477'
down_revision = 'eff90419b076'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phraselist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.String(length=128), nullable=True),
    sa.Column('latin', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('phraselist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.ForeignKeyConstraint(['phraselist_id'], ['phraselist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_created_at'), 'phrase', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrase_created_at'), table_name='phrase')
    op.drop_table('phrase')
    op.drop_table('phraselist')
    # ### end Alembic commands ###
