"""empty message

Revision ID: 08d071784b54
Revises: 45c792fa8449
Create Date: 2017-02-05 16:12:23.372001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d071784b54'
down_revision = '45c792fa8449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answerlist')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'answerlist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answerlist_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'answer', 'answerlist', ['answerlist_id'], ['id'])
    op.create_table('answerlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['creator'], [u'user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
