"""empty message

Revision ID: 321a84b07441
Revises: 
Create Date: 2017-01-29 15:04:01.932572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321a84b07441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('english_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_english_phrase_created_at'), 'english_phrase', ['created_at'], unique=False)
    op.create_table('latin_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latin_phrase_created_at'), 'latin_phrase', ['created_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('answerlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('english_phrase_id', sa.Integer(), nullable=True),
    sa.Column('latin_phrase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['english_phrase_id'], ['english_phrase.id'], ),
    sa.ForeignKeyConstraint(['latin_phrase_id'], ['latin_phrase.id'], )
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('answerlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answerlist_id'], ['answerlist.id'], ),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_created_at'), 'answer', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_created_at'), table_name='answer')
    op.drop_table('answer')
    op.drop_table('tags')
    op.drop_table('answerlist')
    op.drop_table('user')
    op.drop_index(op.f('ix_latin_phrase_created_at'), table_name='latin_phrase')
    op.drop_table('latin_phrase')
    op.drop_index(op.f('ix_english_phrase_created_at'), table_name='english_phrase')
    op.drop_table('english_phrase')
    # ### end Alembic commands ###
