"""empty message

Revision ID: 45c792fa8449
Revises: 5dc95f5e801c
Create Date: 2017-02-02 00:22:15.155140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c792fa8449'
down_revision = '5dc95f5e801c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('english_latin',
    sa.Column('english_phrase_id', sa.Integer(), nullable=True),
    sa.Column('latin_phrase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['english_phrase_id'], ['english_phrase.id'], ),
    sa.ForeignKeyConstraint(['latin_phrase_id'], ['latin_phrase.id'], )
    )
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('english_phrase_id', sa.INTEGER(), nullable=True),
    sa.Column('latin_phrase_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['english_phrase_id'], [u'english_phrase.id'], ),
    sa.ForeignKeyConstraint(['latin_phrase_id'], [u'latin_phrase.id'], )
    )
    op.drop_table('english_latin')
    # ### end Alembic commands ###
