"""empty message

Revision ID: 628473b463f2
Revises: 
Create Date: 2017-01-25 22:09:24.086629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628473b463f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('english_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_english_phrase_created_at'), 'english_phrase', ['created_at'], unique=False)
    op.create_table('latin_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latin_phrase_created_at'), 'latin_phrase', ['created_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('phraselist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('english_phrase_id', sa.Integer(), nullable=True),
    sa.Column('latin_phrase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['english_phrase_id'], ['english_phrase.id'], ),
    sa.ForeignKeyConstraint(['latin_phrase_id'], ['latin_phrase.id'], )
    )
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('phraselist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.ForeignKeyConstraint(['phraselist_id'], ['phraselist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_created_at'), 'phrase', ['created_at'], unique=False)
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('todolist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.ForeignKeyConstraint(['todolist_id'], ['todolist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_created_at'), 'todo', ['created_at'], unique=False)
    op.create_index(op.f('ix_todo_finished_at'), 'todo', ['finished_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_finished_at'), table_name='todo')
    op.drop_index(op.f('ix_todo_created_at'), table_name='todo')
    op.drop_table('todo')
    op.drop_index(op.f('ix_phrase_created_at'), table_name='phrase')
    op.drop_table('phrase')
    op.drop_table('todolist')
    op.drop_table('tags')
    op.drop_table('phraselist')
    op.drop_table('user')
    op.drop_index(op.f('ix_latin_phrase_created_at'), table_name='latin_phrase')
    op.drop_table('latin_phrase')
    op.drop_index(op.f('ix_english_phrase_created_at'), table_name='english_phrase')
    op.drop_table('english_phrase')
    # ### end Alembic commands ###
