"""empty message

Revision ID: 88f82d00c0c1
Revises: 053e1c6ab477
Create Date: 2017-01-24 23:08:21.081055

"""

# revision identifiers, used by Alembic.
revision = '88f82d00c0c1'
down_revision = '053e1c6ab477'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('english_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_english_phrase_created_at'), 'english_phrase', ['created_at'], unique=False)
    op.create_table('latin_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latin_phrase_created_at'), 'latin_phrase', ['created_at'], unique=False)
    op.create_table('tags',
    sa.Column('english_phrase_id', sa.Integer(), nullable=True),
    sa.Column('latin_phrase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['english_phrase_id'], ['english_phrase.id'], ),
    sa.ForeignKeyConstraint(['latin_phrase_id'], ['latin_phrase.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_index(op.f('ix_latin_phrase_created_at'), table_name='latin_phrase')
    op.drop_table('latin_phrase')
    op.drop_index(op.f('ix_english_phrase_created_at'), table_name='english_phrase')
    op.drop_table('english_phrase')
    # ### end Alembic commands ###
