"""empty message

Revision ID: f7be4cf835af
Revises: 4d4a44bff79d
Create Date: 2017-01-29 14:39:31.861559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7be4cf835af'
down_revision = '4d4a44bff79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('phraselist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.username'], ),
    sa.ForeignKeyConstraint(['phraselist_id'], ['phraselist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_created_at'), 'answer', ['created_at'], unique=False)
    op.drop_table('phrase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phrase', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('creator', sa.VARCHAR(length=64), nullable=True),
    sa.Column('phraselist_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint(u'is_correct IN (0, 1)'),
    sa.ForeignKeyConstraint(['creator'], [u'user.username'], ),
    sa.ForeignKeyConstraint(['phraselist_id'], [u'phraselist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_answer_created_at'), table_name='answer')
    op.drop_table('answer')
    # ### end Alembic commands ###
